// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcehskfmxeyejramdoce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjZWhza2ZteGV5ZWpyYW1kb2NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0OTY5NzAsImV4cCI6MjA5MDA3Mjk3MH0.B5xeLOTU7Q3WadM1OM2hUV76XwFqhVfxBh_w5Li1Z7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});